name: share_everywhere
description: Social sharing for all platforms. This plugin is a wrapper for the native share plugin for Android, iOS and Web.
version: 0.0.2
homepage: https://pub.dev
publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  share_plus: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
    assets:
      - icons/facebook.png
      - icons/linkedin.png
      - icons/twitter.png

